name: RPCommands
version: '${version}'
main: com.arisnight.rpcommands.RPCommands
api-version: '1.21'
authors: [ArisNight_(Original), VVrongg(Fork)]
website: https://github.com/VVrongg/RPCommandsExpanded
commands:
  rpcommands:
    description: roleplay commands
  me:
    usage: /me <message>
  do:
    usage: /do <message>
  try:
    usage: /try <message>
permissions:
  rpcommand.reload:
    description: reload plugin
    default: false
  rpcommand.do:
    description: allows you to use the command /do
    default: true
  rpcommand.try:
    description: allows you to use the command /try
    default: true
  rpcommand.me:
    description: allows you to use the command /me
    default: true
